version: '3'

services:
  frontend:
    build:
      context: ./eCommerce_Reactjs
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./ecomAPI
      dockerfile: Dockerfile
    ports:
      - "8003:8003"